CREATE TABLE oracle_types (
    t_CHAR CHAR(2) NOT NULL,
    t_NULL VARCHAR2(2),
    t_VARCHAR VARCHAR2(2) NOT NULL,
    t_VARCHAR2 VARCHAR(2) NOT NULL,
    t_NVARCHAR NCHAR(2) NOT NULL,
    t_NVARCHAR2 NVARCHAR2(2) NOT NULL,
    t_BLOB BLOB NOT NULL,
    t_CLOB CLOB NOT NULL,
    t_NCLOB NCLOB NOT NULL,
    t_NUMBER NUMBER NOT NULL,
    t_NUMBER_1 NUMBER(*,1) NOT NULL,
    t_NUMBER_2 NUMBER(9) NOT NULL,
    t_NUMBER_3 NUMBER(9,2) NOT NULL,
    t_NUMBER_4 NUMBER(9,1) NOT NULL,
    t_NUMBER_5 NUMBER(7,-2) NOT NULL,
    t_BINARY_FLOAT BINARY_FLOAT NOT NULL,
    t_BINARY_DOUBLE BINARY_DOUBLE NOT NULL,
    t_DATE DATE NOT NULL,
    t_TIMESTAMP TIMESTAMP NOT NULL,
    t_TIMESTAMP_TIME_ZONE TIMESTAMP WITH TIME ZONE NOT NULL,
    t_TIMESTAMP_LOCAL TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
);

CREATE TABLE namedInsert (
    t_id NUMBER,
    t_name VARCHAR(20),
    t_address VARCHAR(20)
);

